apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: cp4i-jenkins-ace
  namespace: ace
spec:
  license:
    accept: true
    license: L-APEH-C79J9U
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: true
  enableMetrics: true
  createDashboardUsers: true
  barURL: https://ace-dashboard-dash:3443/v1/directories/file?1bd395f5-7cb8-4379-921c-536ea29a7af7
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  service:
    endpointType: http
  version: '12.0'
  replicas: 1
  logFormat: basic